---
inpackage: true
with-expecter: true
packages:
  github.com/stesla/telnet:
    config:
      dir: './'
    interfaces:
      Conn:
        config:
      EventSink:
        config:
      EventListener:
        config:
      Logger:
        config:
      Option:
        config: