// Code generated by mockery v2.43.2. DO NOT EDIT.

package telnet

import mock "github.com/stretchr/testify/mock"

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Logf provides a mock function with given fields: fmt, v
func (_m *MockLogger) Logf(fmt string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, fmt)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockLogger_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type MockLogger_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//   - fmt string
//   - v ...interface{}
func (_e *MockLogger_Expecter) Logf(fmt interface{}, v ...interface{}) *MockLogger_Logf_Call {
	return &MockLogger_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{fmt}, v...)...)}
}

func (_c *MockLogger_Logf_Call) Run(run func(fmt string, v ...interface{})) *MockLogger_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Logf_Call) Return() *MockLogger_Logf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Logf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Logf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
